name: cross
description: "A new Flutter project."

publish_to:
version: 1.0.0+1

environment:
  sdk: ^3.11.1
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_database: ^11.3.10
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

